// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYkx_pMeKLqiP_uRwbIHtpxUV3UfDQSUk',
    appId: '1:537087069904:web:dcfadeb6e48525892b58d5',
    messagingSenderId: '537087069904',
    projectId: 'missing-ef920',
    authDomain: 'missing-ef920.firebaseapp.com',
    storageBucket: 'missing-ef920.appspot.com',
    measurementId: 'G-X4ZDPD85JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6s3FKTbGYyKvsbdA83zUz0TM2sTXa_TE',
    appId: '1:537087069904:android:59d6706cf07e91602b58d5',
    messagingSenderId: '537087069904',
    projectId: 'missing-ef920',
    storageBucket: 'missing-ef920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrIQqvdGX8LOgqBSMp4koIAswdA3EXbek',
    appId: '1:537087069904:ios:5f1738b6a8b700df2b58d5',
    messagingSenderId: '537087069904',
    projectId: 'missing-ef920',
    storageBucket: 'missing-ef920.appspot.com',
    iosClientId: '537087069904-d3q12inu8u9rh0sdpaq0nva8qabiaoed.apps.googleusercontent.com',
    iosBundleId: 'com.example.missing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrIQqvdGX8LOgqBSMp4koIAswdA3EXbek',
    appId: '1:537087069904:ios:5f1738b6a8b700df2b58d5',
    messagingSenderId: '537087069904',
    projectId: 'missing-ef920',
    storageBucket: 'missing-ef920.appspot.com',
    iosClientId: '537087069904-d3q12inu8u9rh0sdpaq0nva8qabiaoed.apps.googleusercontent.com',
    iosBundleId: 'com.example.missing',
  );
}
